name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build your project
        run: pnpm build
      - name: Ensure dist directory exists
        run: mkdir -p ./dist
      - name: Archive artifact
        run: |
          tar --dereference --hard-dereference \
              --directory "$INPUT_PATH" \
              -cvf "$RUNNER_TEMP/artifact.tar" \
              --exclude=.git \
              --exclude=.github \
              .
        env:
          INPUT_PATH: ./dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: $RUNNER_TEMP/artifact.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
